#!/usr/bin/env ruby

begin
  require 'time'
  
  ls_output = `ls -at /root/.duply-cache/duply_#{ARGV[0]}/*.manifest`
  time_string = ls_output =~ /\.([T\d]+?)Z\.manifest/m && $1

  puts Time.now.to_i - Time.parse(time_string).to_i
  exit 0 # OK
rescue => e
  p e
  exit 3 # Unknown
end
